/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "pklbyhofafkpnrazhifo"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBrbGJ5aG9mYWZrcG5yYXpoaWZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQyODg3NzMsImV4cCI6MjA4OTg2NDc3M30.dbaUtpMP-OkqjR-KgMqSskVcypMRtSWl1JQwTZmkvYA"